'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace PowerballWebService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PowerballWebService._getSoap")>  _
    Public Interface _getSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Powerball", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Powerball() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastPowerballText", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastPowerballText() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastPowerball", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastPowerball() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PBDrawDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PBDrawDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/JustPBDrawDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function JustPBDrawDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PBJackpot", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PBJackpot() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastPowerballGraphics", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastPowerballGraphics() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/JustPBImage", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function JustPBImage() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MegaMillions", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function MegaMillions() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastMegaMillions", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastMegaMillions() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MMDrawDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function MMDrawDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/JustMegaMillionsDrawDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function JustMegaMillionsDrawDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MegaMillionsJackpot", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function MegaMillionsJackpot() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastMegaMillionsGraphics", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastMegaMillionsGraphics() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/JustMMImage", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function JustMMImage() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/JustMegaMillionsImage", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function JustMegaMillionsImage() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cash6", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cash6() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastCash6", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastCash6() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cash6DrawDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cash6DrawDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastCash6Date", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastCash6Date() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastCash6Graphics", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastCash6Graphics() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/P5", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function P5() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP5", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP5() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/P5DrawDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function P5DrawDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP5Date", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP5Date() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP5Graphics", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP5Graphics() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/P4", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function P4() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP4", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP4() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreviousP4", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreviousP4() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP4Graphics", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP4Graphics() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreviousP4Graphic", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreviousP4Graphic() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP4Time", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP4Time() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreviousP4Time", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreviousP4Time() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/P3", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function P3() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP3", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP3() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreviousP3", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreviousP3() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP3Graphic", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP3Graphic() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreviousP3Graphic", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreviousP3Graphic() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LastP3Time", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LastP3Time() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreviousP3Time", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreviousP3Time() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaffleCountdown", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RaffleCountdown() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface _getSoapChannel
        Inherits PowerballWebService._getSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class _getSoapClient
        Inherits System.ServiceModel.ClientBase(Of PowerballWebService._getSoap)
        Implements PowerballWebService._getSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Powerball() As String Implements PowerballWebService._getSoap.Powerball
            Return MyBase.Channel.Powerball
        End Function
        
        Public Function LastPowerballText() As System.Data.DataSet Implements PowerballWebService._getSoap.LastPowerballText
            Return MyBase.Channel.LastPowerballText
        End Function
        
        Public Function LastPowerball() As System.Data.DataSet Implements PowerballWebService._getSoap.LastPowerball
            Return MyBase.Channel.LastPowerball
        End Function
        
        Public Function PBDrawDate() As String Implements PowerballWebService._getSoap.PBDrawDate
            Return MyBase.Channel.PBDrawDate
        End Function
        
        Public Function JustPBDrawDate() As String Implements PowerballWebService._getSoap.JustPBDrawDate
            Return MyBase.Channel.JustPBDrawDate
        End Function
        
        Public Function PBJackpot() As String Implements PowerballWebService._getSoap.PBJackpot
            Return MyBase.Channel.PBJackpot
        End Function
        
        Public Function LastPowerballGraphics() As String Implements PowerballWebService._getSoap.LastPowerballGraphics
            Return MyBase.Channel.LastPowerballGraphics
        End Function
        
        Public Function JustPBImage() As String Implements PowerballWebService._getSoap.JustPBImage
            Return MyBase.Channel.JustPBImage
        End Function
        
        Public Function MegaMillions() As String Implements PowerballWebService._getSoap.MegaMillions
            Return MyBase.Channel.MegaMillions
        End Function
        
        Public Function LastMegaMillions() As System.Data.DataSet Implements PowerballWebService._getSoap.LastMegaMillions
            Return MyBase.Channel.LastMegaMillions
        End Function
        
        Public Function MMDrawDate() As String Implements PowerballWebService._getSoap.MMDrawDate
            Return MyBase.Channel.MMDrawDate
        End Function
        
        Public Function JustMegaMillionsDrawDate() As String Implements PowerballWebService._getSoap.JustMegaMillionsDrawDate
            Return MyBase.Channel.JustMegaMillionsDrawDate
        End Function
        
        Public Function MegaMillionsJackpot() As String Implements PowerballWebService._getSoap.MegaMillionsJackpot
            Return MyBase.Channel.MegaMillionsJackpot
        End Function
        
        Public Function LastMegaMillionsGraphics() As String Implements PowerballWebService._getSoap.LastMegaMillionsGraphics
            Return MyBase.Channel.LastMegaMillionsGraphics
        End Function
        
        Public Function JustMMImage() As String Implements PowerballWebService._getSoap.JustMMImage
            Return MyBase.Channel.JustMMImage
        End Function
        
        Public Function JustMegaMillionsImage() As String Implements PowerballWebService._getSoap.JustMegaMillionsImage
            Return MyBase.Channel.JustMegaMillionsImage
        End Function
        
        Public Function Cash6() As String Implements PowerballWebService._getSoap.Cash6
            Return MyBase.Channel.Cash6
        End Function
        
        Public Function LastCash6() As System.Data.DataSet Implements PowerballWebService._getSoap.LastCash6
            Return MyBase.Channel.LastCash6
        End Function
        
        Public Function Cash6DrawDate() As String Implements PowerballWebService._getSoap.Cash6DrawDate
            Return MyBase.Channel.Cash6DrawDate
        End Function
        
        Public Function LastCash6Date() As String Implements PowerballWebService._getSoap.LastCash6Date
            Return MyBase.Channel.LastCash6Date
        End Function
        
        Public Function LastCash6Graphics() As String Implements PowerballWebService._getSoap.LastCash6Graphics
            Return MyBase.Channel.LastCash6Graphics
        End Function
        
        Public Function P5() As String Implements PowerballWebService._getSoap.P5
            Return MyBase.Channel.P5
        End Function
        
        Public Function LastP5() As System.Data.DataSet Implements PowerballWebService._getSoap.LastP5
            Return MyBase.Channel.LastP5
        End Function
        
        Public Function P5DrawDate() As String Implements PowerballWebService._getSoap.P5DrawDate
            Return MyBase.Channel.P5DrawDate
        End Function
        
        Public Function LastP5Date() As String Implements PowerballWebService._getSoap.LastP5Date
            Return MyBase.Channel.LastP5Date
        End Function
        
        Public Function LastP5Graphics() As String Implements PowerballWebService._getSoap.LastP5Graphics
            Return MyBase.Channel.LastP5Graphics
        End Function
        
        Public Function P4() As String Implements PowerballWebService._getSoap.P4
            Return MyBase.Channel.P4
        End Function
        
        Public Function LastP4() As System.Data.DataSet Implements PowerballWebService._getSoap.LastP4
            Return MyBase.Channel.LastP4
        End Function
        
        Public Function PreviousP4() As System.Data.DataSet Implements PowerballWebService._getSoap.PreviousP4
            Return MyBase.Channel.PreviousP4
        End Function
        
        Public Function LastP4Graphics() As String Implements PowerballWebService._getSoap.LastP4Graphics
            Return MyBase.Channel.LastP4Graphics
        End Function
        
        Public Function PreviousP4Graphic() As String Implements PowerballWebService._getSoap.PreviousP4Graphic
            Return MyBase.Channel.PreviousP4Graphic
        End Function
        
        Public Function LastP4Time() As String Implements PowerballWebService._getSoap.LastP4Time
            Return MyBase.Channel.LastP4Time
        End Function
        
        Public Function PreviousP4Time() As String Implements PowerballWebService._getSoap.PreviousP4Time
            Return MyBase.Channel.PreviousP4Time
        End Function
        
        Public Function P3() As String Implements PowerballWebService._getSoap.P3
            Return MyBase.Channel.P3
        End Function
        
        Public Function LastP3() As System.Data.DataSet Implements PowerballWebService._getSoap.LastP3
            Return MyBase.Channel.LastP3
        End Function
        
        Public Function PreviousP3() As System.Data.DataSet Implements PowerballWebService._getSoap.PreviousP3
            Return MyBase.Channel.PreviousP3
        End Function
        
        Public Function LastP3Graphic() As String Implements PowerballWebService._getSoap.LastP3Graphic
            Return MyBase.Channel.LastP3Graphic
        End Function
        
        Public Function PreviousP3Graphic() As String Implements PowerballWebService._getSoap.PreviousP3Graphic
            Return MyBase.Channel.PreviousP3Graphic
        End Function
        
        Public Function LastP3Time() As String Implements PowerballWebService._getSoap.LastP3Time
            Return MyBase.Channel.LastP3Time
        End Function
        
        Public Function PreviousP3Time() As String Implements PowerballWebService._getSoap.PreviousP3Time
            Return MyBase.Channel.PreviousP3Time
        End Function
        
        Public Function RaffleCountdown() As String Implements PowerballWebService._getSoap.RaffleCountdown
            Return MyBase.Channel.RaffleCountdown
        End Function
    End Class
End Namespace
