'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MetrixStuff
    
    Partial Public Class EmployeeLookup
        
        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtEmployeeId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmployeeId As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''grdEmployeeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeeList As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''pnlAvailableRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAvailableRoles As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''grdEmployeeRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeeRoles As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''pnlAvailablePrograms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAvailablePrograms As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''grdEmployeePrograms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeePrograms As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''pnlAvailableMarkets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAvailableMarkets As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''grdEmployeeMarkets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeeMarkets As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''pnlEmployeePrebook control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEmployeePrebook As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''grdEmployeePrebook control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeePrebook As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''pnlEmployeeSchedules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEmployeeSchedules As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''grdEmployeeSchedules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeeSchedules As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''pnlEmployeeRecaps control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEmployeeRecaps As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''grdEmployeeRecaps control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEmployeeRecaps As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
