'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MetrixStuff

    Partial Public Class MissingSurveySessionLookup

        '''<summary>
        '''MainPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainPanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''TextboxSearchBaId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextboxSearchBaId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextboxSearchDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextboxSearchDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SearchDateCalendarExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchDateCalendarExtender As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''ImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ButtonUpdateSearchDates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonUpdateSearchDates As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TextboxSearchFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextboxSearchFromDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''FromDateCalendarExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FromDateCalendarExtender As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''TextboxSearchToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextboxSearchToDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''GridViewJupiterMobileData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewJupiterMobileData As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''GridViewRecapDcdData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewRecapDcdData As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''GridViewSurveySessionTotals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewSurveySessionTotals As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
