'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RecapDcrResearch

    '''<summary>
    '''TextboxOldRecapId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextboxOldRecapId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextboxNewRecapId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextboxNewRecapId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewOldDcdData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewOldDcdData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewNewDcdData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewNewDcdData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewDcrRecapDcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDcrRecapDcd As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewDcrRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDcrRequest As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewDcrRequestItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDcrRequestItems As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewInteractions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewInteractions As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdateQueryDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateQueryDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SelectedDcrId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedDcrId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SelectedDcrInteractionCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedDcrInteractionCount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SelectedToActivityId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedToActivityId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdateQueryTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateQueryTextbox As Global.System.Web.UI.WebControls.TextBox
End Class
