'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Activity
    Public Property Id As Integer
    Public Property Version As Integer
    Public Property StartDateTime As Nullable(Of Date)
    Public Property EndDateTime As Nullable(Of Date)
    Public Property ActivityType As Nullable(Of Integer)
    Public Property Notes As String
    Public Property RecapId As Nullable(Of Integer)
    Public Property NotExecuted As Nullable(Of Boolean)
    Public Property NotExecutedReasonId As Nullable(Of Integer)
    Public Property NotExecutedReasonNote As String
    Public Property Unscheduled As Nullable(Of Boolean)
    Public Property NonReimbursableSales As Nullable(Of Boolean)
    Public Property VenueId As Nullable(Of Integer)
    Public Property EventId As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ActivationId As Nullable(Of Integer)
    Public Property PromotionTypeId As Nullable(Of Integer)
    Public Property BudgetCodeId As Nullable(Of Integer)
    Public Property SecondaryTimesheetApproverId As Nullable(Of Integer)
    Public Property StrategyType As Nullable(Of Integer)
    Public Property TimeZoneOffset As Nullable(Of Integer)
    Public Property StorageUnitAccountId As Nullable(Of Integer)
    Public Property LastExternalListenersNotifiedDateTime As Nullable(Of Date)
    Public Property ActivityChangeType As Nullable(Of Integer)
    Public Property MarlboroComStatus As Nullable(Of Integer)

    Public Overridable Property Activation As Activation
    Public Overridable Property BudgetCode As BudgetCode
    Public Overridable Property Employee As Employee
    Public Overridable Property PromotionType As PromotionType
    Public Overridable Property ActivityStatusChange As ICollection(Of ActivityStatusChange) = New HashSet(Of ActivityStatusChange)
    Public Overridable Property Recap As ICollection(Of Recap) = New HashSet(Of Recap)
    Public Overridable Property Employee1 As ICollection(Of Employee) = New HashSet(Of Employee)
    Public Overridable Property Employee2 As ICollection(Of Employee) = New HashSet(Of Employee)

End Class
