'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdaptTransferLog
    Public Property Id As Integer
    Public Property LogTypeId As Nullable(Of Integer)
    Public Property GMREmployeeId As String
    Public Property IsSuccess As Nullable(Of Boolean)
    Public Property EmployeeObject As String
    Public Property ResponseMessage As String
    Public Property Message As String
    Public Property Source As String
    Public Property StackTrace As String
    Public Property LogDateTime As Nullable(Of Date)

End Class
