'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AmendmentDefinition
    Public Property Id As Integer
    Public Property Name As String
    Public Property RequiresReviewToIssue As Nullable(Of Boolean)
    Public Property AmendmentType As Nullable(Of Integer)
    Public Property ReportName As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property AmendmentDefinitionPayment As ICollection(Of AmendmentDefinitionPayment) = New HashSet(Of AmendmentDefinitionPayment)
    Public Overridable Property AmendmentDefinitionRule As ICollection(Of AmendmentDefinitionRule) = New HashSet(Of AmendmentDefinitionRule)
    Public Overridable Property ContractAmendment As ICollection(Of ContractAmendment) = New HashSet(Of ContractAmendment)
    Public Overridable Property ContractRequestAmendment As ICollection(Of ContractRequestAmendment) = New HashSet(Of ContractRequestAmendment)
    Public Overridable Property ContractDefinition As ICollection(Of ContractDefinition) = New HashSet(Of ContractDefinition)
    Public Overridable Property PromotionType As ICollection(Of PromotionType) = New HashSet(Of PromotionType)

End Class
