'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AmendmentDefinitionPayment
    Public Property Id As Integer
    Public Property AmendmentDefinitionId As Integer
    Public Property Name As String
    Public Property LowRange As Nullable(Of Decimal)
    Public Property HighRange As Nullable(Of Decimal)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property BudgetCode As String
    Public Property GLCode As String
    Public Property Type As Nullable(Of Integer)

    Public Overridable Property AmendmentDefinition As AmendmentDefinition

End Class
