'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AssignedBrand
    Public Property Id As Integer
    Public Property Name As String
    Public Property InvoiceNumberPrefix As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property IsActive As Nullable(Of Boolean)
    Public Property BudgetCodeId As Nullable(Of Integer)

    Public Overridable Property BudgetCode As BudgetCode
    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property Item As ICollection(Of Item) = New HashSet(Of Item)
    Public Overridable Property Orders As ICollection(Of Orders) = New HashSet(Of Orders)

End Class
