'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BrandAmbassador
    Public Property PersonId As Integer
    Public Property LegacyBrandAmbassadorId As Nullable(Of Integer)
    Public Property BrandAmbassadorType As Nullable(Of Integer)
    Public Property ClearedDate As Nullable(Of Date)
    Public Property ClearedToWork As Nullable(Of Boolean)
    Public Property AdaptStatus As String
    Public Property HireType As Nullable(Of Short)
    Public Property AgencyName As String
    Public Property EmergencyContact As String
    Public Property EmergencyPhone As String
    Public Property EmergencyRelation As String
    Public Property CreatedFromAdapt As Nullable(Of Date)
    Public Property LastUpdateFromAdapt As Nullable(Of Date)

    Public Overridable Property Employee As Employee
    Public Overridable Property BrandAmbassadorMoba As ICollection(Of BrandAmbassadorMoba) = New HashSet(Of BrandAmbassadorMoba)

End Class
