'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BrandAmbassadorMoba
    Public Property Id As Integer
    Public Property PersonId As Integer
    Public Property AssignedDate As Nullable(Of Date)
    Public Property MarketId As Nullable(Of Integer)
    Public Property TeamStartDate As Nullable(Of Date)
    Public Property Achievements As String
    Public Property InterestingFacts As String
    Public Property ManagerQuote As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Integer

    Public Overridable Property BrandAmbassador As BrandAmbassador

End Class
