'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CancellationReason
    Public Property Id As Integer
    Public Property Description As String
    Public Property IsPayable As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property IsMSACompliant As Nullable(Of Boolean)
    Public Property LocationType As Nullable(Of Integer)
    Public Property IsActive As Nullable(Of Boolean)

    Public Overridable Property Recap As ICollection(Of Recap) = New HashSet(Of Recap)

End Class
