'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractDefinition
    Public Property Id As Integer
    Public Property Name As String
    Public Property ProgramId As Integer
    Public Property ReportName As String
    Public Property ExpirationDate As Nullable(Of Date)
    Public Property HasMFP As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property BSFReportName As String
    Public Property IsMinimumPricing As Nullable(Of Boolean)
    Public Property MinimumMarkup As Nullable(Of Decimal)

    Public Overridable Property Contract As ICollection(Of Contract) = New HashSet(Of Contract)
    Public Overridable Property Program As Program
    Public Overridable Property ContractDefinitionPayment As ICollection(Of ContractDefinitionPayment) = New HashSet(Of ContractDefinitionPayment)
    Public Overridable Property ContractDefinitionRule As ICollection(Of ContractDefinitionRule) = New HashSet(Of ContractDefinitionRule)
    Public Overridable Property ContractRequest As ICollection(Of ContractRequest) = New HashSet(Of ContractRequest)
    Public Overridable Property AmendmentDefinition As ICollection(Of AmendmentDefinition) = New HashSet(Of AmendmentDefinition)
    Public Overridable Property PromotionType As ICollection(Of PromotionType) = New HashSet(Of PromotionType)

End Class
