'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractPayment
    Public Property Id As Integer
    Public Property ContractId As Integer
    Public Property ContractDefinitionPaymentId As Nullable(Of Integer)
    Public Property PaymentAmount As Nullable(Of Decimal)
    Public Property PaymentTierId As Nullable(Of Integer)
    Public Property Type As Nullable(Of Integer)
    Public Property IsOverridden As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property Contract As Contract
    Public Overridable Property ContractDefinitionPayment As ContractDefinitionPayment

End Class
