'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractRequestDocument
    Public Property Id As Integer
    Public Property ContractRequestId As Integer
    Public Property DocumentData As Byte()
    Public Property ContractDocumentType As Nullable(Of Integer)
    Public Property ContractDocumentVersion As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property ApprovedById As Nullable(Of Integer)
    Public Property ApprovedDateTime As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ContractRequest As ContractRequest

End Class
