'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractVisibilityAmendmentVisibilityItemRequest
    Public Property ContractVisibilityAmendmentId As Integer
    Public Property VisibilityItemRequestId As Integer
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property VisibilityItemRequest As VisibilityItemRequest

End Class
