'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractAmendment
    Public Property Id As Integer
    Public Property ContractId As Integer
    Public Property AmendmentDefinitionId As Integer
    Public Property ContractRequestAmendmentId As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property TerminatedDateTime As Nullable(Of Date)
    Public Property ApprovedDateTime As Nullable(Of Date)
    Public Property ApprovedById As Nullable(Of Integer)

    Public Overridable Property AmendmentDefinition As AmendmentDefinition
    Public Overridable Property Contract As Contract
    Public Overridable Property Employee As Employee
    Public Overridable Property ContractAmendmentDocument As ICollection(Of ContractAmendmentDocument) = New HashSet(Of ContractAmendmentDocument)
    Public Overridable Property ContractVisibilityAmendment As ContractVisibilityAmendment

End Class
