'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractDefinitionPayment
    Public Property Id As Integer
    Public Property ContractDefinitionId As Integer
    Public Property Name As String
    Public Property Type As Nullable(Of Integer)
    Public Property LowRange As Nullable(Of Decimal)
    Public Property HighRange As Nullable(Of Decimal)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property BudgetCode As String
    Public Property GLCode As String

    Public Overridable Property ContractDefinition As ContractDefinition
    Public Overridable Property ContractPayment As ICollection(Of ContractPayment) = New HashSet(Of ContractPayment)
    Public Overridable Property ContractRequestPayment As ICollection(Of ContractRequestPayment) = New HashSet(Of ContractRequestPayment)

End Class
