'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractType
    Public Property Id As Integer
    Public Property ProgramId As Nullable(Of Integer)
    Public Property Name As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property LumpSumPmtFlag As Nullable(Of Boolean)
    Public Property UserDefinedAmtFlag As Nullable(Of Boolean)
    Public Property TobLicReqFlag As Nullable(Of Boolean)
    Public Property LumpSumSalesPmtFlag As Nullable(Of Boolean)
    Public Property UserDefinedSalesAmtFlag As Nullable(Of Boolean)
    Public Property BackBarSales As Nullable(Of Boolean)
    Public Property ScheduleB As Nullable(Of Boolean)
    Public Property MFPSalesBonus As Nullable(Of Boolean)
    Public Property PermVisibility As Nullable(Of Boolean)
    Public Property Website As Nullable(Of Boolean)
    Public Property Events As Nullable(Of Boolean)

End Class
