'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContractRequest
    Public Property Id As Integer
    Public Property VenueProgramDetailId As Integer
    Public Property ContractDefinitionId As Integer
    Public Property Status As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property ContractRequestType As Nullable(Of Integer)

    Public Overridable Property ContractDefinition As ContractDefinition
    Public Overridable Property VenueProgramDetail As VenueProgramDetail
    Public Overridable Property ContractRequestAmendment As ICollection(Of ContractRequestAmendment) = New HashSet(Of ContractRequestAmendment)
    Public Overridable Property ContractRequestComment As ICollection(Of ContractRequestComment) = New HashSet(Of ContractRequestComment)
    Public Overridable Property ContractRequestDocument As ICollection(Of ContractRequestDocument) = New HashSet(Of ContractRequestDocument)
    Public Overridable Property ContractRequestPayment As ICollection(Of ContractRequestPayment) = New HashSet(Of ContractRequestPayment)
    Public Overridable Property ContractRequestStatusChange As ICollection(Of ContractRequestStatusChange) = New HashSet(Of ContractRequestStatusChange)

End Class
