'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DateDimension
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property Day As String
    Public Property DaySuffix As String
    Public Property DayOfWeek As String
    Public Property DOWInMonth As Byte
    Public Property DayOfYear As Integer
    Public Property WeekOfYear As Byte
    Public Property WeekOfMonth As Byte
    Public Property Month As String
    Public Property MonthName As String
    Public Property Quarter As Byte
    Public Property QuarterName As String
    Public Property Year As String
    Public Property StandardDate As String
    Public Property HolidayText As String

End Class
