'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DCDSetup
    Public Property Id As Integer
    Public Property EventId As Nullable(Of Integer)
    Public Property SurveyId As Nullable(Of Integer)
    Public Property MarketCode As String
    Public Property ARCProgramNumber As String
    Public Property SitelPOBox As String
    Public Property SitelPhase As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property VenueNumber As String
    Public Property ShouldSendToARC As Boolean
    Public Property LastSentToARCDateTime As Nullable(Of Date)

    Public Overridable Property [Event] As [Event]

End Class
