'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property PersonId As Integer
    Public Property LegacyEmployeeId As Nullable(Of Integer)
    Public Property LegacyRoleId As Nullable(Of Integer)
    Public Property LegacyDefaultMarketId As Nullable(Of Integer)
    Public Property GMREmployeeId As String
    Public Property UserId As Nullable(Of System.Guid)
    Public Property UserName As String
    Public Property Bilingual As Nullable(Of Boolean)
    Public Property Travel As Nullable(Of Boolean)
    Public Property UniformSize As String
    Public Property Title As String
    Public Property AcceptedEUA As Nullable(Of Boolean)
    Public Property DateAcceptedEUA As Nullable(Of Date)
    Public Property LastLoginDateTime As Nullable(Of Date)
    Public Property NumberOfLogins As Nullable(Of Integer)
    Public Property ManagerId As Nullable(Of Integer)
    Public Property DCDBAId As String

    Public Overridable Property Activation As ICollection(Of Activation) = New HashSet(Of Activation)
    Public Overridable Property Activation1 As ICollection(Of Activation) = New HashSet(Of Activation)
    Public Overridable Property Activity As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property Alert As ICollection(Of Alert) = New HashSet(Of Alert)
    Public Overridable Property BrandAmbassador As BrandAmbassador
    Public Overridable Property Contract As ICollection(Of Contract) = New HashSet(Of Contract)
    Public Overridable Property ContractAmendment As ICollection(Of ContractAmendment) = New HashSet(Of ContractAmendment)
    Public Overridable Property Person As Person
    Public Overridable Property EmployeeMarket As ICollection(Of EmployeeMarket) = New HashSet(Of EmployeeMarket)
    Public Overridable Property EmployeeProgram As ICollection(Of EmployeeProgram) = New HashSet(Of EmployeeProgram)
    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property Employee1 As ICollection(Of Employee) = New HashSet(Of Employee)
    Public Overridable Property Employee2 As Employee
    Public Overridable Property PersonImage As ICollection(Of PersonImage) = New HashSet(Of PersonImage)
    Public Overridable Property RecapDocument As ICollection(Of RecapDocument) = New HashSet(Of RecapDocument)
    Public Overridable Property RecapInventory As ICollection(Of RecapInventory) = New HashSet(Of RecapInventory)
    Public Overridable Property RecapStaff As ICollection(Of RecapStaff) = New HashSet(Of RecapStaff)
    Public Overridable Property StaffHoursRecap As ICollection(Of StaffHoursRecap) = New HashSet(Of StaffHoursRecap)
    Public Overridable Property TaskRecipient As ICollection(Of TaskRecipient) = New HashSet(Of TaskRecipient)
    Public Overridable Property TrainingDateAttendee As ICollection(Of TrainingDateAttendee) = New HashSet(Of TrainingDateAttendee)
    Public Overridable Property VenuePayment As ICollection(Of VenuePayment) = New HashSet(Of VenuePayment)
    Public Overridable Property Activation2 As ICollection(Of Activation) = New HashSet(Of Activation)
    Public Overridable Property Activation3 As ICollection(Of Activation) = New HashSet(Of Activation)
    Public Overridable Property Activity1 As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property Activity2 As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property Role As ICollection(Of Role) = New HashSet(Of Role)

End Class
