'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Event]
    Public Property Id As Integer
    Public Property Version As Nullable(Of Integer)
    Public Property Name As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property EstimatedInteractions As Nullable(Of Integer)
    Public Property EstimatedAttendance As Nullable(Of Integer)
    Public Property Notes As String
    Public Property VenueId As Nullable(Of Integer)
    Public Property PromotionTypeId As Nullable(Of Integer)
    Public Property BrandId As Nullable(Of Integer)
    Public Property EventCategoryId As Nullable(Of Integer)
    Public Property PrimaryManagerId As Nullable(Of Integer)
    Public Property BudgetCodeId As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property UsesDCD As Nullable(Of Boolean)
    Public Property DCDSetupStatus As Nullable(Of Integer)
    Public Property ActivationId As Nullable(Of Integer)
    Public Property StorageUnitAccountId As Nullable(Of Integer)

    Public Overridable Property AssignedBrand As AssignedBrand
    Public Overridable Property BudgetCode As BudgetCode
    Public Overridable Property DCDSetup As ICollection(Of DCDSetup) = New HashSet(Of DCDSetup)
    Public Overridable Property Employee As Employee
    Public Overridable Property EventCategory As EventCategory
    Public Overridable Property PromotionType As PromotionType
    Public Overridable Property StorageUnitAccount As StorageUnitAccount
    Public Overridable Property Venue As Venue
    Public Overridable Property EventDocument As ICollection(Of EventDocument) = New HashSet(Of EventDocument)

End Class
