'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FulfillmentCompany
    Public Property Id As Integer
    Public Property Name As String
    Public Property RequiresApproval As Boolean
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property City As String
    Public Property State As String
    Public Property Country As String
    Public Property Zip As String
    Public Property CategoryId As Nullable(Of Integer)
    Public Property IsActive As Boolean
    Public Property CreatedDateTime As Date
    Public Property ModifiedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedByUserId As System.Guid
    Public Property RequiresAvailableQuantities As Nullable(Of Boolean)
    Public Property IsReviewable As Boolean
    Public Property Version As Nullable(Of Integer)
    Public Property NotifyOfShipmentChanges As Boolean

    Public Overridable Property FulfillmentCompanyShippingCarrier As ICollection(Of FulfillmentCompanyShippingCarrier) = New HashSet(Of FulfillmentCompanyShippingCarrier)
    Public Overridable Property Item As ICollection(Of Item) = New HashSet(Of Item)
    Public Overridable Property Shipment As ICollection(Of Shipment) = New HashSet(Of Shipment)

End Class
