'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ImportFilesStatus
    Public Property Id As Integer
    Public Property FileId As Nullable(Of Integer)
    Public Property FileName As String
    Public Property FileType As String
    Public Property SQLStmt As String
    Public Property Status As Nullable(Of Boolean)

End Class
