'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InteractionCCNMeasurementData
    Public Property ActivityID As Nullable(Of Integer)
    Public Property InteractionID As System.Guid
    Public Property CCN As Integer
    Public Property DOIStatus As String
    Public Property DOIDate As Nullable(Of Date)
    Public Property ATCFirstName As String
    Public Property ATCZipCode As String
    Public Property ATCEmailCipher As Byte()
    Public Property Incentives As String
    Public Property Cigarettes As String
    Public Property Menthol As String
    Public Property CigRegBrand As String
    Public Property CigOtherBrand As String
    Public Property MST As String
    Public Property MSTRegBrand As String
    Public Property MSTFlavor As String
    Public Property MSTCut As String
    Public Property Snus As String
    Public Property SnusBrand As String
    Public Property Cigar As String
    Public Property CigarBrand As String
    Public Property IsContactable As String
    Public Property ReceiptDateTime As Date
    Public Property CreatedDateTime As Date
    Public Property LastUpdatedDateTime As Date
    Public Property Active As Boolean

End Class
