'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventoryDestructionRequest
    Public Property Id As Integer
    Public Property Name As String
    Public Property ProgramId As Integer
    Public Property RequiresPhysicalCount As Boolean
    Public Property Status As Integer
    Public Property ApprovedById As Nullable(Of Integer)
    Public Property ApprovedDateTime As Nullable(Of Date)
    Public Property CreatedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Integer
    Public Property InventoryDestructionRequestSelectedItemType As Integer

    Public Overridable Property InventoryDestructionRequestComment As ICollection(Of InventoryDestructionRequestComment) = New HashSet(Of InventoryDestructionRequestComment)
    Public Overridable Property InventoryDestructionRequestItem As ICollection(Of InventoryDestructionRequestItem) = New HashSet(Of InventoryDestructionRequestItem)
    Public Overridable Property InventoryDestructionRequestStatusChange As ICollection(Of InventoryDestructionRequestStatusChange) = New HashSet(Of InventoryDestructionRequestStatusChange)

End Class
