'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventoryDestructionRequestItem
    Public Property Id As Integer
    Public Property InventoryDestructionRequestId As Integer
    Public Property StorageUnitAccountItemInventoryId As Integer
    Public Property Quantity As Integer
    Public Property Status As Integer
    Public Property HasUpload As Boolean
    Public Property CreatedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Integer
    Public Property IsDamaged As Boolean
    Public Property ApprovedQuantity As Integer

    Public Overridable Property InventoryDestructionRequest As InventoryDestructionRequest
    Public Overridable Property InventoryDestructionRequestItemComment As ICollection(Of InventoryDestructionRequestItemComment) = New HashSet(Of InventoryDestructionRequestItemComment)
    Public Overridable Property InventoryDestructionRequestItemDocument As ICollection(Of InventoryDestructionRequestItemDocument) = New HashSet(Of InventoryDestructionRequestItemDocument)
    Public Overridable Property InventoryDestructionRequestItemImage As ICollection(Of InventoryDestructionRequestItemImage) = New HashSet(Of InventoryDestructionRequestItemImage)
    Public Overridable Property InventoryDestructionRequestItemStatusChange As ICollection(Of InventoryDestructionRequestItemStatusChange) = New HashSet(Of InventoryDestructionRequestItemStatusChange)

End Class
