'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventoryAdjustmentRequest
    Public Property Id As Integer
    Public Property QuantitySnapshot As Nullable(Of Integer)
    Public Property RequestedInventoryLevel As Integer
    Public Property ApprovedInventoryLevel As Nullable(Of Integer)
    Public Property AdjustmentType As Integer
    Public Property Status As Integer
    Public Property DateRequested As Nullable(Of Date)
    Public Property FieldCommentText As String
    Public Property FieldCommentName As String
    Public Property FieldCommentDate As Nullable(Of Date)
    Public Property HQCommentText As String
    Public Property HQCommentName As String
    Public Property HQCommentDate As Nullable(Of Date)
    Public Property ChangedByHQ As Boolean
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property InventoryAdjustmentRequestStatusChange As ICollection(Of InventoryAdjustmentRequestStatusChange) = New HashSet(Of InventoryAdjustmentRequestStatusChange)

End Class
