'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventoryRequest
    Public Property Id As Integer
    Public Property StorageUnitAccountId As Integer
    Public Property ShipmentId As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property Name As String
    Public Property DateRequested As Nullable(Of Date)
    Public Property RequestType As Nullable(Of Integer)
    Public Property ChangedByHQ As Boolean
    Public Property FieldCommentText As String
    Public Property FieldCommentName As String
    Public Property FieldCommentDate As Nullable(Of Date)
    Public Property HQCommentText As String
    Public Property HQCommentName As String
    Public Property HQCommentDate As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property ProgramId As Nullable(Of Integer)
    Public Property ParentProgramId As Nullable(Of Integer)

    Public Overridable Property Shipment As Shipment
    Public Overridable Property StorageUnitAccount As StorageUnitAccount
    Public Overridable Property InventoryRequestItem As ICollection(Of InventoryRequestItem) = New HashSet(Of InventoryRequestItem)

End Class
