'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventoryTransactionType
    Public Property Id As Integer
    Public Property Comments As String
    Public Property Description As String
    Public Property Name As String
    Public Property ShortHelpText As String
    Public Property LongHelpText As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ItemInventoryTransaction As ICollection(Of ItemInventoryTransaction) = New HashSet(Of ItemInventoryTransaction)

End Class
