'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Item
    Public Property Id As Integer
    Public Property BrandId As Nullable(Of Integer)
    Public Property FulfillmentCompanyId As Nullable(Of Integer)
    Public Property ItemTypeId As Nullable(Of Integer)
    Public Property ItemCategoryId As Nullable(Of Integer)
    Public Property UnitOfMeasure As Nullable(Of Integer)
    Public Property Name As String
    Public Property Description As String
    Public Property RetailPrice As Nullable(Of Decimal)
    Public Property PartNumber As String
    Public Property StatusDescription As String
    Public Property Comments As String
    Public Property SerialRangeStart As String
    Public Property SerialRangeEnd As String
    Public Property UnitMeasureQuantity As Nullable(Of Integer)
    Public Property Weight As Nullable(Of Double)
    Public Property ProductShelfLife As Nullable(Of Integer)
    Public Property AllowNegativeInventories As Nullable(Of Boolean)
    Public Property HasImage As Nullable(Of Boolean)
    Public Property IsSerialized As Nullable(Of Boolean)
    Public Property IsBranded As Boolean
    Public Property IsHazardousMaterial As Boolean
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property RequiresUnitCostOnFulfillment As Boolean
    Public Property RequiresExpirationDateOnReceipt As Boolean
    Public Property AssignedBrandId As Nullable(Of Integer)
    Public Property SortOrder As Nullable(Of Integer)

    Public Overridable Property AssignedBrand As AssignedBrand
    Public Overridable Property Brand As Brand
    Public Overridable Property FulfillmentCompany As FulfillmentCompany
    Public Overridable Property InventoryRequestItem As ICollection(Of InventoryRequestItem) = New HashSet(Of InventoryRequestItem)
    Public Overridable Property ItemProgramPhysicalCountSchedule As ICollection(Of ItemProgramPhysicalCountSchedule) = New HashSet(Of ItemProgramPhysicalCountSchedule)
    Public Overridable Property ItemCategory As ItemCategory
    Public Overridable Property ItemType As ItemType
    Public Overridable Property ItemUnitMeasure As ItemUnitMeasure
    Public Overridable Property ItemActiveDates As ICollection(Of ItemActiveDates) = New HashSet(Of ItemActiveDates)
    Public Overridable Property ItemImage As ICollection(Of ItemImage) = New HashSet(Of ItemImage)
    Public Overridable Property ItemStorageUnitAccount As ICollection(Of ItemStorageUnitAccount) = New HashSet(Of ItemStorageUnitAccount)
    Public Overridable Property PromotionTypeDefaultItem As ICollection(Of PromotionTypeDefaultItem) = New HashSet(Of PromotionTypeDefaultItem)
    Public Overridable Property ShipmentAvailableQuantity As ICollection(Of ShipmentAvailableQuantity) = New HashSet(Of ShipmentAvailableQuantity)
    Public Overridable Property ShipmentItem As ICollection(Of ShipmentItem) = New HashSet(Of ShipmentItem)
    Public Overridable Property VenueItemInventoryAdjustmentRequest As ICollection(Of VenueItemInventoryAdjustmentRequest) = New HashSet(Of VenueItemInventoryAdjustmentRequest)
    Public Overridable Property VenueReceiptItem As ICollection(Of VenueReceiptItem) = New HashSet(Of VenueReceiptItem)
    Public Overridable Property ItemTag As ICollection(Of ItemTag) = New HashSet(Of ItemTag)
    Public Overridable Property PromotionType As ICollection(Of PromotionType) = New HashSet(Of PromotionType)

End Class
