'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ItemInventoryTransaction
    Public Property Id As Long
    Public Property RecapInventoryId As Nullable(Of Integer)
    Public Property RecapNonReimbursableItemId As Nullable(Of Integer)
    Public Property ShipmentItemReceiptId As Nullable(Of Integer)
    Public Property ItemInventoryId As Nullable(Of Integer)
    Public Property TypeId As Integer
    Public Property Qty As Nullable(Of Integer)
    Public Property Description As String
    Public Property Comments As String
    Public Property CommentName As String
    Public Property CommentText As String
    Public Property CommentDate As Nullable(Of Date)
    Public Property TransactionDate As Date
    Public Property PreviousBalance As Nullable(Of Integer)
    Public Property ProductExpirationDate As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property OrderItemId As Nullable(Of Integer)
    Public Property VisibilityItemRequestId As Nullable(Of Integer)
    Public Property RecapReimbursableItemId As Nullable(Of Integer)

    Public Overridable Property InventoryTransactionType As InventoryTransactionType
    Public Overridable Property ItemInventory As ItemInventory
    Public Overridable Property OrderItem As OrderItem
    Public Overridable Property ShipmentItemReceipt As ShipmentItemReceipt
    Public Overridable Property VenueItemInventoryAdjustmentRequest As ICollection(Of VenueItemInventoryAdjustmentRequest) = New HashSet(Of VenueItemInventoryAdjustmentRequest)

End Class
