'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LocationType
    Public Property Id As Integer
    Public Property Name As String
    Public Property DataTable As String
    Public Property LegacyName As String

    Public Overridable Property PromotionType As ICollection(Of PromotionType) = New HashSet(Of PromotionType)
    Public Overridable Property VenueProgramDetail As ICollection(Of VenueProgramDetail) = New HashSet(Of VenueProgramDetail)

End Class
