'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Market
    Public Property Id As Integer
    Public Property Name As String
    Public Property ShortName As String
    Public Property MarketCode As String
    Public Property RegionId As Nullable(Of Integer)
    Public Property AdaptMarketName As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ProgramMarketDetail As ICollection(Of ProgramMarketDetail) = New HashSet(Of ProgramMarketDetail)
    Public Overridable Property VenuePayment As ICollection(Of VenuePayment) = New HashSet(Of VenuePayment)
    Public Overridable Property VenueProgramDetail As ICollection(Of VenueProgramDetail) = New HashSet(Of VenueProgramDetail)
    Public Overridable Property PromotionType As ICollection(Of PromotionType) = New HashSet(Of PromotionType)

End Class
