'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MasterProgram
    Public Property Id As Integer
    Public Property Name As String
    Public Property ShortName As String
    Public Property ApplicationId As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property ContractProgramName As String
    Public Property ContractYear As Nullable(Of Integer)
    Public Property ContractingStartDate As Nullable(Of Date)
    Public Property ContractingEndDate As Nullable(Of Date)
    Public Property ContractVisits As Nullable(Of Integer)
    Public Property IsActive As Nullable(Of Boolean)
    Public Property ProgramCode As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property StorageUnitAccount As ICollection(Of StorageUnitAccount) = New HashSet(Of StorageUnitAccount)

End Class
