'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Menu
    Public Property Id As Integer
    Public Property ParentMenuId As Nullable(Of Integer)
    Public Property LinkText As String
    Public Property LinkURL As String
    Public Property NewWindow As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property IsActive As Boolean
    Public Property Version As Nullable(Of Integer)
    Public Property SortOrder As Nullable(Of Integer)

End Class
