'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Note
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property Author As String
    Public Property Text As String
    Public Property CreatedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ShipmentNote As ICollection(Of ShipmentNote) = New HashSet(Of ShipmentNote)

End Class
