'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OperatorAddress
    Public Property Id As Integer
    Public Property OperatorId As Nullable(Of Integer)
    Public Property AddressAddressLine1 As String
    Public Property AddressAddressLine2 As String
    Public Property AddressCity As String
    Public Property AddressState As String
    Public Property AddressPostalCode As String
    Public Property ContactName As String
    Public Property ContactTitle As String
    Public Property ContactEmail As String
    Public Property ContactPhone As String
    Public Property ContactFax As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property [Operator] As [Operator]

End Class
