'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Operator]
    Public Property Id As Integer
    Public Property Name As String
    Public Property BusinessName As String
    Public Property BusinessOrganizationOther As String
    Public Property FedId As String
    Public Property BusinessDescription As String
    Public Property SBADisadvantaged As Nullable(Of Boolean)
    Public Property CertificationDenial As Nullable(Of Boolean)
    Public Property GMRFamilyRelation As Nullable(Of Boolean)
    Public Property Complete As Nullable(Of Boolean)
    Public Property BusinessClassificationType As Nullable(Of Integer)
    Public Property MinorityBusinessClassificationType As Nullable(Of Integer)
    Public Property BusinessOrganizationType As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property BusinessClassificationType1 As BusinessClassificationType
    Public Overridable Property BusinessOrganizationType1 As BusinessOrganizationType
    Public Overridable Property MinorityBusinessClassificationType1 As MinorityBusinessClassificationType
    Public Overridable Property OperatorAddress As ICollection(Of OperatorAddress) = New HashSet(Of OperatorAddress)
    Public Overridable Property VenueOperatorInsurance As ICollection(Of VenueOperatorInsurance) = New HashSet(Of VenueOperatorInsurance)

End Class
