'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Orders
    Public Property Id As Integer
    Public Property InvoiceNumber As String
    Public Property Version As Integer
    Public Property VenueId As Nullable(Of Integer)
    Public Property EstimatedDeliveryDate As Nullable(Of Date)
    Public Property ActualDeliveryDate As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property CityTaxPercentage As Nullable(Of Double)
    Public Property CountyTaxPercentage As Nullable(Of Double)
    Public Property StateTaxPercentage As Nullable(Of Double)
    Public Property HasPackingSlip As Nullable(Of Boolean)
    Public Property IsProcessed As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property StorageUnitAccountId As Nullable(Of Integer)
    Public Property ProgramId As Nullable(Of Integer)
    Public Property SpecialTaxPercentage As Nullable(Of Double)
    Public Property LocalTaxPercentage As Nullable(Of Double)
    Public Property AssignedBrandId As Nullable(Of Integer)
    Public Property OrderType As Nullable(Of Integer)

    Public Overridable Property AssignedBrand As AssignedBrand
    Public Overridable Property OrderHistory As ICollection(Of OrderHistory) = New HashSet(Of OrderHistory)
    Public Overridable Property OrderItem As ICollection(Of OrderItem) = New HashSet(Of OrderItem)
    Public Overridable Property OrderPackingSlip As ICollection(Of OrderPackingSlip) = New HashSet(Of OrderPackingSlip)
    Public Overridable Property OrderPreProcessorFileOrder As ICollection(Of OrderPreProcessorFileOrder) = New HashSet(Of OrderPreProcessorFileOrder)
    Public Overridable Property StorageUnitAccount As StorageUnitAccount
    Public Overridable Property OrderStatusChange As ICollection(Of OrderStatusChange) = New HashSet(Of OrderStatusChange)

End Class
