'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderItem
    Public Property Id As Integer
    Public Property Version As Integer
    Public Property Quantity As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property StorageUnitAccountItemInventoryId As Nullable(Of Integer)
    Public Property OrderId As Nullable(Of Integer)
    Public Property OrderStatus As Nullable(Of Integer)
    Public Property LineItemNumber As Nullable(Of Integer)
    Public Property MinimumMarkup As Nullable(Of Double)
    Public Property MinimumMarkupType As Nullable(Of Integer)
    Public Property ProductUnitCost As Nullable(Of Double)
    Public Property WasOverridden As Boolean

    Public Overridable Property ItemInventory As ItemInventory
    Public Overridable Property ItemInventoryTransaction As ICollection(Of ItemInventoryTransaction) = New HashSet(Of ItemInventoryTransaction)
    Public Overridable Property Orders As Orders

End Class
