'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentTier
    Public Property Id As Integer
    Public Property Name As String
    Public Property LowRange As Decimal
    Public Property HighRange As Decimal
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property LowGoal As Nullable(Of Integer)
    Public Property HighGoal As Nullable(Of Integer)
    Public Property TierNumber As Nullable(Of Byte)

End Class
