'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentTierAvailability
    Public Property PaymentTierId As Integer
    Public Property ContractDefinitionPaymentId As Integer
    Public Property MarketSizeId As Integer

    Public Overridable Property PaymentTierAvailability1 As PaymentTierAvailability
    Public Overridable Property PaymentTierAvailability2 As PaymentTierAvailability

End Class
