'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentTierAmendmentAvailability
    Public Property PaymentTierId As Integer
    Public Property AmendmentDefinitionPaymentId As Integer
    Public Property MarketSizeId As Integer

    Public Overridable Property PaymentTierAmendmentAvailability1 As PaymentTierAmendmentAvailability
    Public Overridable Property PaymentTierAmendmentAvailability2 As PaymentTierAmendmentAvailability

End Class
