'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person
    Public Property Id As Integer
    Public Property Version As Integer
    Public Property FirstName As String
    Public Property MiddleName As String
    Public Property LastName As String
    Public Property Gender As Nullable(Of Integer)
    Public Property Email As String
    Public Property CustomerNumber As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property Notes As String
    Public Property HasImage As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property DeactivatedDateTime As Nullable(Of Date)
    Public Property Title As String

    Public Overridable Property Employee As Employee
    Public Overridable Property PersonAddress As ICollection(Of PersonAddress) = New HashSet(Of PersonAddress)
    Public Overridable Property PersonPhoneNumber As ICollection(Of PersonPhoneNumber) = New HashSet(Of PersonPhoneNumber)
    Public Overridable Property VenueContact As ICollection(Of VenueContact) = New HashSet(Of VenueContact)
    Public Overridable Property VenueProgramDetailConfirmationStatus As ICollection(Of VenueProgramDetailConfirmationStatus) = New HashSet(Of VenueProgramDetailConfirmationStatus)

End Class
