'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PhysicalCountSchedule
    Public Property Id As Integer
    Public Property PhysicalCountFrequency As Integer
    Public Property StartDayOfPeriod As Nullable(Of Integer)
    Public Property StartTimeOfDay As Nullable(Of Date)
    Public Property CloseDayOfPeriod As Nullable(Of Integer)
    Public Property CloseTimeOfDay As Nullable(Of Date)
    Public Property IsActive As Boolean
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ItemProgramPhysicalCountSchedule As ICollection(Of ItemProgramPhysicalCountSchedule) = New HashSet(Of ItemProgramPhysicalCountSchedule)
    Public Overridable Property PhysicalCountFrequency1 As PhysicalCountFrequency

End Class
