'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PostalCode
    Public Property Id As Integer
    Public Property Code As String
    Public Property City As String
    Public Property County As String
    Public Property State As String
    Public Property UspsCity As String
    Public Property CountyFips As String
    Public Property IsDefaultCounty As Boolean
    Public Property IsDefaultCity As Boolean
    Public Property IsManualAddition As Boolean

End Class
