'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PromotionType
    Public Property Id As Integer
    Public Property Version As Integer
    Public Property Name As String
    Public Property CategoryId As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property ProgramId As Nullable(Of Integer)
    Public Property BrandId As Nullable(Of Integer)
    Public Property InventoryRecappingType As Nullable(Of Integer)
    Public Property DCDRecappingType As Nullable(Of Integer)
    Public Property NonReimbursableSalesAllowed As Nullable(Of Boolean)

    Public Overridable Property Activity As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property PromotionTypeCategory As PromotionTypeCategory
    Public Overridable Property PromotionTypeDefaultItem As ICollection(Of PromotionTypeDefaultItem) = New HashSet(Of PromotionTypeDefaultItem)
    Public Overridable Property PromotionTypeDocumentAttribute As ICollection(Of PromotionTypeDocumentAttribute) = New HashSet(Of PromotionTypeDocumentAttribute)
    Public Overridable Property PromotionTypeQuestion As ICollection(Of PromotionTypeQuestion) = New HashSet(Of PromotionTypeQuestion)
    Public Overridable Property PromotionTypeRequirement As ICollection(Of PromotionTypeRequirement) = New HashSet(Of PromotionTypeRequirement)
    Public Overridable Property AmendmentDefinition As ICollection(Of AmendmentDefinition) = New HashSet(Of AmendmentDefinition)
    Public Overridable Property ContractDefinition As ICollection(Of ContractDefinition) = New HashSet(Of ContractDefinition)
    Public Overridable Property Item As ICollection(Of Item) = New HashSet(Of Item)
    Public Overridable Property LocationType As ICollection(Of LocationType) = New HashSet(Of LocationType)
    Public Overridable Property Market As ICollection(Of Market) = New HashSet(Of Market)
    Public Overridable Property Survey As ICollection(Of Survey) = New HashSet(Of Survey)

End Class
