'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Recap
    Public Property Id As Integer
    Public Property VenueId As Integer
    Public Property StartDateTime As Date
    Public Property EndDateTime As Date
    Public Property Attendance As Integer
    Public Property StrategyType As Integer
    Public Property PromotionTypeId As Integer
    Public Property EndedEarly As Boolean
    Public Property HasNonReimbursableSales As Boolean
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property CancellationReasonId As Nullable(Of Integer)
    Public Property ApprovedById As Nullable(Of Integer)
    Public Property ApprovedDateTime As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property ProgramId As Nullable(Of Integer)
    Public Property IsRemoved As Nullable(Of Boolean)
    Public Property ContractId As Nullable(Of Integer)
    Public Property ActivityId As Nullable(Of Integer)
    Public Property StorageUnitAccountId As Nullable(Of Integer)
    Public Property FirstSurveyDateTime As Nullable(Of Date)
    Public Property LastSurveyDateTime As Nullable(Of Date)

    Public Overridable Property Activity As Activity
    Public Overridable Property CancellationReason As CancellationReason
    Public Overridable Property Venue As Venue
    Public Overridable Property RecapConfirmationStatus As ICollection(Of RecapConfirmationStatus) = New HashSet(Of RecapConfirmationStatus)
    Public Overridable Property RecapDCD As ICollection(Of RecapDCD) = New HashSet(Of RecapDCD)
    Public Overridable Property RecapDocumentHistory As ICollection(Of RecapDocumentHistory) = New HashSet(Of RecapDocumentHistory)
    Public Overridable Property RecapInventory As ICollection(Of RecapInventory) = New HashSet(Of RecapInventory)
    Public Overridable Property RecapStaff As ICollection(Of RecapStaff) = New HashSet(Of RecapStaff)
    Public Overridable Property RecapVoucher As ICollection(Of RecapVoucher) = New HashSet(Of RecapVoucher)
    Public Overridable Property StorageUnitAccount As ICollection(Of StorageUnitAccount) = New HashSet(Of StorageUnitAccount)

End Class
