'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecapReimbursableBAPItem
    Public Property RecapReimbursableItemId As Integer
    Public Property PostPromo As Nullable(Of Integer)
    Public Property DuringPromo As Nullable(Of Integer)

End Class
