'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecapDCD
    Public Property Id As Integer
    Public Property RecapId As Integer
    Public Property DCDNumber As Integer
    Public Property TotalSurveys As Integer
    Public Property AS2124 As Nullable(Of Integer)
    Public Property AS2529 As Nullable(Of Integer)
    Public Property AS30Plus As Nullable(Of Integer)
    Public Property Email As Nullable(Of Integer)
    Public Property Phone As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property BAId As String
    Public Property SurveySessionId As Nullable(Of System.Guid)
    Public Property EmployeeId As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property IsRemoved As Nullable(Of Boolean)
    Public Property TotalCheckIns As Nullable(Of Integer)

    Public Overridable Property Recap As Recap
    Public Overridable Property RecapDataCorrectionRequest As ICollection(Of RecapDataCorrectionRequest) = New HashSet(Of RecapDataCorrectionRequest)

End Class
