'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecapDataCorrectionRequestItem
    Public Property Id As Integer
    Public Property RecapDataCorrectionRequestId As Integer
    Public Property InteractionId As Nullable(Of System.Guid)
    Public Property OriginalBAId As String
    Public Property OriginalActivityId As Nullable(Of Integer)
    Public Property CorrectedEmployeeId As Nullable(Of Integer)
    Public Property CorrectedActivityId As Nullable(Of Integer)
    Public Property SurveyStartTime As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property RecapDataCorrectionRequest As RecapDataCorrectionRequest

End Class
