'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecapDocument
    Public Property Id As Integer
    Public Property RecapId As Integer
    Public Property DocumentData As Byte()
    Public Property DocumentName As String
    Public Property RequiresReview As Nullable(Of Boolean)
    Public Property PromotionTypeDocumentAttributeId As Integer
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property ApprovedById As Nullable(Of Integer)
    Public Property ApprovedDateTime As Nullable(Of Date)
    Public Property RejectedById As Nullable(Of Integer)
    Public Property RejectedDateTime As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property VenueManagerName As String
    Public Property IsPaperless As Nullable(Of Boolean)
    Public Property ManagerSignatureData As Byte()
    Public Property VenueSignatureData As Byte()
    Public Property CompletedDateTime As Nullable(Of Date)
    Public Property SignedById As Nullable(Of Integer)

    Public Overridable Property Employee As Employee

End Class
