'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecapReimbursableItemVenueItemInventory
    Public Property RecapReimbursableItemId As Integer
    Public Property VenueItemInventoryId As Integer

    Public Overridable Property VenueItemInventory As VenueItemInventory

End Class
