'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecapDataCorrectionRequest
    Public Property Id As Integer
    Public Property RecapDCDId As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property FieldCommentText As String
    Public Property FieldCommentName As String
    Public Property FieldCommentDate As Nullable(Of Date)
    Public Property ApproveRejectCommentText As String
    Public Property ApproveRejectCommentName As String
    Public Property ApproveRejectCommentDate As Nullable(Of Date)
    Public Property ApprovedById As Nullable(Of Integer)
    Public Property ApprovedDateTime As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property RecapDataCorrectionRequestItem As ICollection(Of RecapDataCorrectionRequestItem) = New HashSet(Of RecapDataCorrectionRequestItem)
    Public Overridable Property RecapDCD As RecapDCD

End Class
