'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RoleUserAction
    Public Property RoleId As Integer
    Public Property UserActionId As Integer
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property Role As Role
    Public Overridable Property UserAction As UserAction

End Class
