'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Role
    Public Property Id As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property IsActive As Nullable(Of Boolean)
    Public Property Version As Nullable(Of Integer)
    Public Property ParentRoleId As Nullable(Of Integer)
    Public Property IsCategory As Nullable(Of Boolean)

    Public Overridable Property Role1 As ICollection(Of Role) = New HashSet(Of Role)
    Public Overridable Property Role2 As Role
    Public Overridable Property RoleUserAction As ICollection(Of RoleUserAction) = New HashSet(Of RoleUserAction)
    Public Overridable Property Employee As ICollection(Of Employee) = New HashSet(Of Employee)

End Class
