'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Shipment
    Public Property Id As Integer
    Public Property ShipmentType As String
    Public Property ProgramId As Nullable(Of Integer)
    Public Property FulfillmentCompanyId As Nullable(Of Integer)
    Public Property RequestedDeliveryDate As Nullable(Of Date)
    Public Property EstimatedShipDate As Nullable(Of Date)
    Public Property Name As String
    Public Property OrderDate As Date
    Public Property Status As Nullable(Of Integer)
    Public Property PurchaseOrderNumber As String
    Public Property InventoryRequestConversion As Boolean
    Public Property FieldCommentName As String
    Public Property FieldCommentText As String
    Public Property FieldCommentDate As Nullable(Of Date)
    Public Property GeneralCommentName As String
    Public Property GeneralCommentText As String
    Public Property GeneralCommentDate As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property RequireBoxInfo As Nullable(Of Boolean)

    Public Overridable Property FulfillmentCompany As FulfillmentCompany
    Public Overridable Property InventoryRequest As ICollection(Of InventoryRequest) = New HashSet(Of InventoryRequest)
    Public Overridable Property ShipmentApproval As ICollection(Of ShipmentApproval) = New HashSet(Of ShipmentApproval)
    Public Overridable Property ShipmentAvailableQuantity As ICollection(Of ShipmentAvailableQuantity) = New HashSet(Of ShipmentAvailableQuantity)
    Public Overridable Property ShipmentNote As ICollection(Of ShipmentNote) = New HashSet(Of ShipmentNote)
    Public Overridable Property ShipmentPackingSlip As ICollection(Of ShipmentPackingSlip) = New HashSet(Of ShipmentPackingSlip)
    Public Overridable Property ShipmentReceiptDocument As ICollection(Of ShipmentReceiptDocument) = New HashSet(Of ShipmentReceiptDocument)
    Public Overridable Property ShipmentRejection As ICollection(Of ShipmentRejection) = New HashSet(Of ShipmentRejection)
    Public Overridable Property ShipmentStatusChange As ICollection(Of ShipmentStatusChange) = New HashSet(Of ShipmentStatusChange)
    Public Overridable Property ShipmentItem As ICollection(Of ShipmentItem) = New HashSet(Of ShipmentItem)

End Class
