'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentProblemReport
    Public Property Id As Integer
    Public Property ShipmentItemReceiptId As Nullable(Of Integer)
    Public Property ShipmentProblemType As Integer
    Public Property Comment As String
    Public Property CreatedByUserId As System.Guid
    Public Property CreatedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ShipmentItemFulfillmentId As Nullable(Of Integer)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ShipmentItemFulfillment As ShipmentItemFulfillment
    Public Overridable Property ShipmentItemReceipt As ShipmentItemReceipt

End Class
