'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentNote
    Public Property ShipmentId As Integer
    Public Property NoteId As Integer
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property Note As Note
    Public Overridable Property Shipment As Shipment

End Class
