'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentAvailableQuantity
    Public Property Id As Integer
    Public Property ShipmentId As Integer
    Public Property ItemId As Integer
    Public Property AvailableQuantity As Integer
    Public Property CreatedByUserId As System.Guid
    Public Property CreatedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property Item As Item
    Public Overridable Property Shipment As Shipment

End Class
