'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentItemStatusChange
    Public Property Id As Integer
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ShipmentItemId As Nullable(Of Integer)
    Public Property ShipmentItemStatusChangeId As Nullable(Of Integer)
    Public Property NewStatus As Nullable(Of Integer)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ShipmentItem As ShipmentItem
    Public Overridable Property ShipmentItemStatusChange1 As ICollection(Of ShipmentItemStatusChange) = New HashSet(Of ShipmentItemStatusChange)
    Public Overridable Property ShipmentItemStatusChange2 As ShipmentItemStatusChange

End Class
