'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentItemBox
    Public Property Id As Integer
    Public Property Quantity As Integer
    Public Property TrackingNumber As String
    Public Property ArrivalDate As Nullable(Of Date)
    Public Property ShipmentItemFulfillmentId As Integer
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ShipmentItemFulfillment As ShipmentItemFulfillment

End Class
