'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShippingCarrier
    Public Property Id As Integer
    Public Property Name As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property IsActive As Boolean

    Public Overridable Property FulfillmentCompanyShippingCarrier As ICollection(Of FulfillmentCompanyShippingCarrier) = New HashSet(Of FulfillmentCompanyShippingCarrier)
    Public Overridable Property ShipmentItem As ICollection(Of ShipmentItem) = New HashSet(Of ShipmentItem)

End Class
