'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentItem
    Public Property Id As Integer
    Public Property ShipmentId As Integer
    Public Property DestinationStorageUnitAccountId As Nullable(Of Integer)
    Public Property SourceItemInventoryId As Nullable(Of Integer)
    Public Property ItemId As Integer
    Public Property ShipmentItemReceiptId As Nullable(Of Integer)
    Public Property ShippingCarrierId As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property ItemNumber As Integer
    Public Property CarrierName As String
    Public Property CustomerServiceOrderNumber As String
    Public Property ShippingAddressType As Nullable(Of Integer)
    Public Property ReturnShippingAddressType As Nullable(Of Integer)
    Public Property ShipDate As Nullable(Of Date)
    Public Property Quantity As Integer
    Public Property ShipQuantity As Nullable(Of Integer)
    Public Property AssignmentNotAllowed As Nullable(Of Boolean)
    Public Property AssignmentOverridden As Nullable(Of Boolean)
    Public Property ShippingLocationName As String
    Public Property ShippingLocationCustomerNumber As String
    Public Property ShippingLocationAddressAddressLine1 As String
    Public Property ShippingLocationAddressAddressLine2 As String
    Public Property ShippingLocationAddressCity As String
    Public Property ShippingLocationAddressState As String
    Public Property ShippingLocationAddressPostalCode As String
    Public Property ShippingLocationPhoneNumberNumber As String
    Public Property ShippingLocationPhoneNumberPhoneNumberType As Nullable(Of Integer)
    Public Property TrackingNumber As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property SourceAvailableQuantity As Nullable(Of Integer)
    Public Property OrderBundleId As String
    Public Property Version As Nullable(Of Integer)
    Public Property ResendPartnerOrder As Boolean
    Public Property VendorPurchaseOrderNumber As String
    Public Property ShippingLocationPhoneNumberMobileProviderType As Nullable(Of Short)
    Public Property ShippingLocationPhoneNumberIsPrimary As Nullable(Of Boolean)

    Public Overridable Property Item As Item
    Public Overridable Property ItemInventory As ItemInventory
    Public Overridable Property Shipment As Shipment
    Public Overridable Property StorageUnitAccount As StorageUnitAccount
    Public Overridable Property ShipmentItemFulfillment As ICollection(Of ShipmentItemFulfillment) = New HashSet(Of ShipmentItemFulfillment)
    Public Overridable Property ShipmentItemStatusChange As ICollection(Of ShipmentItemStatusChange) = New HashSet(Of ShipmentItemStatusChange)
    Public Overridable Property ShipmentItemReceipt As ICollection(Of ShipmentItemReceipt) = New HashSet(Of ShipmentItemReceipt)
    Public Overridable Property ShippingCarrier As ShippingCarrier

End Class
