'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storage
    Public Property Id As Integer
    Public Property Name As String
    Public Property MarketId As Nullable(Of Integer)
    Public Property Description As String
    Public Property ShippingLocationName As String
    Public Property ShippingLocationCustomerNumber As String
    Public Property ShippingLocationAddressAddressLine1 As String
    Public Property ShippingLocationAddressAddressLine2 As String
    Public Property County As String
    Public Property ShippingLocationAddressCity As String
    Public Property ShippingLocationAddressState As String
    Public Property ShippingLocationAddressPostalCode As String
    Public Property Country As String
    Public Property Fax As String
    Public Property ShippingLocationPhoneNumberNumber As String
    Public Property ShippingLocationPhoneNumberPhoneNumberType As Nullable(Of Integer)
    Public Property Comments As String
    Public Property Size As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property ShippingLocationPhoneNumberMobileProviderType As Nullable(Of Short)
    Public Property ShippingLocationPhoneNumberIsPrimary As Nullable(Of Boolean)

    Public Overridable Property StorageUnit As ICollection(Of StorageUnit) = New HashSet(Of StorageUnit)

End Class
