'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StorageUnitAccountItemInventoryAdjustmentRequest
    Public Property InventoryAdjustmentRequestId As Integer
    Public Property StorageUnitAccountItemInventoryId As Integer
    Public Property ItemInventoryTransactionId As Nullable(Of Long)

End Class
