'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StorageUnitAccount
    Public Property Id As Integer
    Public Property StorageUnitId As Integer
    Public Property ManagerId As Nullable(Of Integer)
    Public Property ProgramId As Nullable(Of Integer)
    Public Property MarketId As Nullable(Of Integer)
    Public Property Name As String
    Public Property IsActive As Boolean
    Public Property CreatedByUserId As System.Guid
    Public Property CreatedDateTime As Date
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property WholesaleLicenseNumber As String

    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property InventoryRequest As ICollection(Of InventoryRequest) = New HashSet(Of InventoryRequest)
    Public Overridable Property ItemStorageUnitAccount As ICollection(Of ItemStorageUnitAccount) = New HashSet(Of ItemStorageUnitAccount)
    Public Overridable Property MasterProgram As MasterProgram
    Public Overridable Property Orders As ICollection(Of Orders) = New HashSet(Of Orders)
    Public Overridable Property PhysicalCount As ICollection(Of PhysicalCount) = New HashSet(Of PhysicalCount)
    Public Overridable Property ShipmentItem As ICollection(Of ShipmentItem) = New HashSet(Of ShipmentItem)
    Public Overridable Property StorageUnit As StorageUnit
    Public Overridable Property StorageUnitAccountDefaultShippingAddress As ICollection(Of StorageUnitAccountDefaultShippingAddress) = New HashSet(Of StorageUnitAccountDefaultShippingAddress)
    Public Overridable Property Recap As ICollection(Of Recap) = New HashSet(Of Recap)
    Public Overridable Property ItemInventory As ICollection(Of ItemInventory) = New HashSet(Of ItemInventory)

End Class
