'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StorageUnitAccountDefaultShippingAddress
    Public Property Id As Integer
    Public Property StorageUnitAccountId As Integer
    Public Property ShippingAddressType As Integer
    Public Property OtherShippingLocationName As String
    Public Property OtherShippingLocationCustomerNumber As String
    Public Property OtherShippingLocationPhoneNumberNumber As String
    Public Property OtherShippingLocationAddressAddressLine1 As String
    Public Property OtherShippingLocationAddressAddressLine2 As String
    Public Property OtherShippingLocationAddressCity As String
    Public Property OtherShippingLocationAddressState As String
    Public Property OtherShippingLocationAddressPostalCode As String
    Public Property OtherShippingLocationPhoneNumberPhoneNumberType As Nullable(Of Integer)
    Public Property OtherShippingLocationPhoneNumberIsPrimary As Nullable(Of Boolean)
    Public Property OtherShippingLocationPhoneNumberMobileProviderType As Nullable(Of Short)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property StorageUnitAccount As StorageUnitAccount

End Class
