'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StorageUnit
    Public Property Id As Integer
    Public Property StorageId As Nullable(Of Integer)
    Public Property Name As String
    Public Property UnitNumber As String
    Public Property UnitSize As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property Storage As Storage
    Public Overridable Property StorageUnitAccount As ICollection(Of StorageUnitAccount) = New HashSet(Of StorageUnitAccount)

End Class
