'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Survey
    Public Property Id As Integer
    Public Property Name As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property DcdSurveyId As Nullable(Of System.Guid)
    Public Property ProgramId As Nullable(Of Integer)

    Public Overridable Property Program As Program
    Public Overridable Property PromotionType As ICollection(Of PromotionType) = New HashSet(Of PromotionType)

End Class
