'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaskStep
    Public Property Id As Integer
    Public Property TaskStepDefinitionId As Integer
    Public Property TaskId As Integer
    Public Property CreatedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Integer

    Public Overridable Property Task As Task
    Public Overridable Property TaskRecipient As ICollection(Of TaskRecipient) = New HashSet(Of TaskRecipient)
    Public Overridable Property TaskStepDefinition As TaskStepDefinition

End Class
