'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaskCategory
    Public Property Id As Integer
    Public Property Name As String
    Public Property DisplayName As String
    Public Property CreatedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Integer

    Public Overridable Property AlertDefinition As ICollection(Of AlertDefinition) = New HashSet(Of AlertDefinition)
    Public Overridable Property TaskDefinition As ICollection(Of TaskDefinition) = New HashSet(Of TaskDefinition)

End Class
