'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Task
    Public Property Id As Integer
    Public Property TargetId As Integer
    Public Property TaskDefinitionId As Integer
    Public Property ProgramId As Nullable(Of Integer)
    Public Property TaskStatus As Nullable(Of Integer)
    Public Property CreatedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedDateTime As Date
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Integer

    Public Overridable Property Program As Program
    Public Overridable Property TaskDefinition As TaskDefinition
    Public Overridable Property TaskKey As ICollection(Of TaskKey) = New HashSet(Of TaskKey)
    Public Overridable Property TaskStep As ICollection(Of TaskStep) = New HashSet(Of TaskStep)

End Class
