'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Team
    Public Property Id As Integer
    Public Property LegacyTeamId As Nullable(Of Integer)
    Public Property Version As Integer
    Public Property Name As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ProgramMarketDetailId As Nullable(Of Integer)
    Public Property ManagerId As Nullable(Of Integer)
    Public Property DefaultWeeklyGoal As Nullable(Of Integer)
    Public Property DefaultWeeklyHours As Nullable(Of Integer)
    Public Property DefaultWeeklyBudget As Nullable(Of Decimal)
    Public Property BudgetCodeId As Nullable(Of Integer)
    Public Property TeamNumber As Nullable(Of Integer)

    Public Overridable Property Activation As ICollection(Of Activation) = New HashSet(Of Activation)
    Public Overridable Property StaffHoursRecap As ICollection(Of StaffHoursRecap) = New HashSet(Of StaffHoursRecap)
    Public Overridable Property TeamWeekDetail As ICollection(Of TeamWeekDetail) = New HashSet(Of TeamWeekDetail)

End Class
