'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TeamWeekDetail
    Public Property Id As Integer
    Public Property TeamId As Integer
    Public Property ProgramWeekId As Integer
    Public Property WeekGoal As Nullable(Of Integer)
    Public Property WeekHours As Nullable(Of Integer)
    Public Property WeekBudget As Nullable(Of Decimal)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

    Public Overridable Property ProgramWeek As ProgramWeek
    Public Overridable Property Team As Team

End Class
