'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TimeZone
    Public Property Id As Integer
    Public Property TimeZoneOffset As Integer
    Public Property Name As String
    Public Property IsActive As Boolean
    Public Property IsDefault As Boolean
    Public Property ShortName As String

End Class
