'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TimeDimension
    Public Property Id As Nullable(Of Integer)
    Public Property Time As String
    Public Property Hour As String
    Public Property MilitaryHour As String
    Public Property Minute As String
    Public Property Second As String
    Public Property AmPm As String
    Public Property StandardTime As String

End Class
