'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Topic
    Public Property Id As Integer
    Public Property Name As String
    Public Property CreatedDateTime As Date
    Public Property ModifiedDateTime As Date
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedByUserId As System.Guid
    Public Property Version As Integer

    Public Overridable Property Training As ICollection(Of Training) = New HashSet(Of Training)

End Class
