'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserSession
    Public Property Id As System.Guid
    Public Property SessionId As String
    Public Property UserName As String
    Public Property Expires As Date
    Public Property ClaimSet As String

End Class
