'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueItemInventoryAdjustmentRequest
    Public Property InventoryAdjustmentRequestId As Integer
    Public Property VenueId As Integer
    Public Property ItemId As Integer

    Public Overridable Property Item As Item
    Public Overridable Property Venue As Venue
    Public Overridable Property ItemInventoryTransaction As ICollection(Of ItemInventoryTransaction) = New HashSet(Of ItemInventoryTransaction)

End Class
