'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueContact
    Public Property Id As Integer
    Public Property VenueId As Nullable(Of Integer)
    Public Property PersonId As Nullable(Of Integer)
    Public Property IsPrimary As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property ShouldReceiveNMAC As Nullable(Of Boolean)

    Public Overridable Property Person As Person
    Public Overridable Property Venue As Venue

End Class
