'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueItemInventory
    Public Property ItemInventoryId As Integer
    Public Property VenueId As Integer
    Public Property VenueReceiptId As Nullable(Of Integer)

    Public Overridable Property RecapReimbursableItemVenueItemInventory As ICollection(Of RecapReimbursableItemVenueItemInventory) = New HashSet(Of RecapReimbursableItemVenueItemInventory)

End Class
