'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueOperatorInsurance
    Public Property Id As Integer
    Public Property VenueNumber As String
    Public Property VenueId As Integer
    Public Property OperatorId As Integer
    Public Property InsuranceCompanyName As String
    Public Property InsuranceCompanyContact As String
    Public Property InsuranceCompanyPhone As String
    Public Property InsuranceCompanyFax As String
    Public Property CreatedDateTime As Date
    Public Property ModifiedDateTime As Date
    Public Property CreatedByUserId As String
    Public Property ModifiedByUserId As String
    Public Property Version As Integer
    Public Property InsuranceCompanyEmail As String

    Public Overridable Property [Operator] As [Operator]
    Public Overridable Property Venue As Venue

End Class
