'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenuePhoneNumber
    Public Property Id As Integer
    Public Property VenueId As Integer
    Public Property PhoneNumberNumber As String
    Public Property PhoneNumberPhoneNumberType As Nullable(Of Integer)
    Public Property PhoneNumberMobileProviderType As Nullable(Of Integer)
    Public Property PhoneNumberIsPrimary As Nullable(Of Boolean)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)

End Class
