'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueDocument
    Public Property Id As Integer
    Public Property VenueId As Integer
    Public Property Name As String
    Public Property DocumentData As Byte()
    Public Property VenueDocumentType As Integer
    Public Property EffectiveFrom As Nullable(Of Date)
    Public Property EffectiveTo As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)
    Public Property LegacyId As Nullable(Of Integer)
    Public Property DocumentNumber As String
    Public Property VenueDocumentDefinitionId As Nullable(Of Integer)
    Public Property IsArchived As Boolean

End Class
