'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueDocumentDefinition
    Public Property Id As Integer
    Public Property Name As String
    Public Property AvailableState As String
    Public Property AvailableCounty As String
    Public Property AvailableCity As String
    Public Property VenueDocumentType As Integer
    Public Property LicenseType As Nullable(Of Integer)
    Public Property IsActive As Boolean
    Public Property Comment As String
    Public Property RequiresExpirationDate As Boolean
    Public Property RequiresIdNumber As Boolean
    Public Property IsRequiredForExecution As Boolean
    Public Property IsRequiredForSales As Boolean
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Integer

End Class
