'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueQuestionAnswerLocationTypeProgram
    Public Property Id As Integer
    Public Property ProgramId As Nullable(Of Integer)
    Public Property LocationType As Nullable(Of Integer)
    Public Property VenueQuestionId As Nullable(Of Integer)
    Public Property VenueAnswerId As Nullable(Of Integer)
    Public Property DependentVenueQuestionId As Nullable(Of Integer)
    Public Property DependentVenueAnswerId As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property Version As Nullable(Of Integer)

End Class
