'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venue
    Public Property Id As Integer
    Public Property Number As String
    Public Property Name As String
    Public Property AddressAddressLine1 As String
    Public Property AddressAddressLine2 As String
    Public Property AddressCity As String
    Public Property County As String
    Public Property AddressState As String
    Public Property AddressPostalCode As String
    Public Property Geocode As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property NeighborhoodId As Nullable(Of Integer)
    Public Property OperatorId As Nullable(Of Integer)
    Public Property Website As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property AddressCode As String
    Public Property VendorCode As String
    Public Property ShouldSendToARC As Nullable(Of Boolean)
    Public Property LastSentToARCDateTime As Nullable(Of Date)
    Public Property PrimaryNMACRecipientEmail As String
    Public Property TimeZoneId As Integer
    Public Property VenueChangeType As Integer
    Public Property LastExternalListenersNotifiedDateTime As Nullable(Of Date)
    Public Property SMSName As String

    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property Neighborhood As Neighborhood
    Public Overridable Property Recap As ICollection(Of Recap) = New HashSet(Of Recap)
    Public Overridable Property VenueComment As ICollection(Of VenueComment) = New HashSet(Of VenueComment)
    Public Overridable Property VenueContact As ICollection(Of VenueContact) = New HashSet(Of VenueContact)
    Public Overridable Property VenueImage As ICollection(Of VenueImage) = New HashSet(Of VenueImage)
    Public Overridable Property VenueItemInventoryAdjustmentRequest As ICollection(Of VenueItemInventoryAdjustmentRequest) = New HashSet(Of VenueItemInventoryAdjustmentRequest)
    Public Overridable Property VenueNumberHistory As ICollection(Of VenueNumberHistory) = New HashSet(Of VenueNumberHistory)
    Public Overridable Property VenueProgramDetail As ICollection(Of VenueProgramDetail) = New HashSet(Of VenueProgramDetail)
    Public Overridable Property VenueOperatorInsurance As ICollection(Of VenueOperatorInsurance) = New HashSet(Of VenueOperatorInsurance)
    Public Overridable Property VenueReceipt As ICollection(Of VenueReceipt) = New HashSet(Of VenueReceipt)

End Class
