'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueProgramDetailAttribute
    Public Property Id As Integer
    Public Property VenueProgramDetailId As Integer
    Public Property VenueNumber As String
    Public Property LocationType As Nullable(Of Integer)
    Public Property AgeRequirementType As Nullable(Of Integer)
    Public Property AgeVerificationType As Nullable(Of Integer)
    Public Property VenueNotes As String
    Public Property AllowSellingEvents As Nullable(Of Boolean)
    Public Property DirectDepositFlag As Nullable(Of Boolean)
    Public Property DirectDepositDate As Nullable(Of Date)
    Public Property VenueQualifies As String
    Public Property TaxExempt As Nullable(Of Boolean)
    Public Property Website As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property HoldsLicenses As Nullable(Of Boolean)
    Public Property VenueStatus As String

    Public Overridable Property VenueProgramDetail As VenueProgramDetail

End Class
