'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueImage
    Public Property Id As Integer
    Public Property VenueId As Nullable(Of Integer)
    Public Property Description As String
    Public Property VenueImageType As Nullable(Of Integer)
    Public Property ImageData As Byte()
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property ImageFileName As String

    Public Overridable Property Venue As Venue
    Public Overridable Property VenueImageType1 As VenueImageType

End Class
