'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenuePaymentCheckProcessing
    Public Property CheckNumber As Integer
    Public Property VoucherNumber As Integer
    Public Property Amount As Decimal
    Public Property CheckFileId As String
    Public Property CheckDateTime As Date
    Public Property CheckYear As String
    Public Property VendorId As String
    Public Property VendorName As String
    Public Property AddressCode As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property Address3 As String

End Class
