'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueProgramDetailSchedule
    Public Property Id As Integer
    Public Property VenueProgramDetailId As Integer
    Public Property DayId As Integer
    Public Property IsOpen As Nullable(Of Boolean)
    Public Property OpenFrom As String
    Public Property OpenTo As String
    Public Property AOFOpenFrom As String
    Public Property AOFOpenTo As String
    Public Property HappyHour As Nullable(Of Boolean)
    Public Property Evening As Nullable(Of Boolean)
    Public Property LateNight As Nullable(Of Boolean)
    Public Property DrinkSpecials As Nullable(Of Boolean)
    Public Property SportingEvents As Nullable(Of Boolean)
    Public Property LiveMusic As Nullable(Of Boolean)
    Public Property ThemeNight As Nullable(Of Boolean)
    Public Property OtherSpecialEvents As String
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As System.Guid
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property Trivia As Nullable(Of Boolean)

    Public Overridable Property VenueProgramDetail As VenueProgramDetail

End Class
