'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueProgramDetailConfirmationStatus
    Public Property Id As Integer
    Public Property VenueProgramDetailId As Integer
    Public Property VenueTabCategory As Nullable(Of Integer)
    Public Property ConfirmedDateTime As Nullable(Of Date)
    Public Property ConfirmedBy As Nullable(Of Integer)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property IsSaved As Nullable(Of Boolean)

    Public Overridable Property Person As Person
    Public Overridable Property VenueProgramDetail As VenueProgramDetail

End Class
