'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VisibilityItemRequest
    Public Property Id As Integer
    Public Property ItemId As Integer
    Public Property VenueId As Integer
    Public Property InstallationType As Nullable(Of Integer)
    Public Property InstallationSurfaceType As Nullable(Of Integer)
    Public Property InstallationZoneType As Nullable(Of Integer)
    Public Property LocationDescription As String
    Public Property Status As Nullable(Of Integer)
    Public Property HasImage As Nullable(Of Boolean)
    Public Property ClearedForInstallation As Nullable(Of Boolean)
    Public Property VisibilityVenueItemInventoryId As Nullable(Of Integer)
    Public Property InstallationDateTime As Nullable(Of Date)
    Public Property CreatedDateTime As Nullable(Of Date)
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedByUserId As Nullable(Of System.Guid)
    Public Property ModifiedDateTime As Nullable(Of Date)
    Public Property Version As Nullable(Of Integer)
    Public Property LegacyRequestNumber As Nullable(Of Integer)

    Public Overridable Property ContractRequestVisibilityAmendmentVisibilityItemRequest As ICollection(Of ContractRequestVisibilityAmendmentVisibilityItemRequest) = New HashSet(Of ContractRequestVisibilityAmendmentVisibilityItemRequest)
    Public Overridable Property ContractVisibilityAmendmentVisibilityItemRequest As ICollection(Of ContractVisibilityAmendmentVisibilityItemRequest) = New HashSet(Of ContractVisibilityAmendmentVisibilityItemRequest)
    Public Overridable Property InstallationSurfaceType1 As InstallationSurfaceType
    Public Overridable Property InstallationType1 As InstallationType
    Public Overridable Property InstallationZoneType1 As InstallationZoneType
    Public Overridable Property VisibilityItemRequestStatus As VisibilityItemRequestStatus
    Public Overridable Property VisibilityItemRequestImage As ICollection(Of VisibilityItemRequestImage) = New HashSet(Of VisibilityItemRequestImage)
    Public Overridable Property VisibilityItemRequestStatusChange As ICollection(Of VisibilityItemRequestStatusChange) = New HashSet(Of VisibilityItemRequestStatusChange)

End Class
