'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VisibilityVenueItemInventory
    Public Property ItemInventoryId As Integer
    Public Property InstallationType As Nullable(Of Integer)
    Public Property InstallationSurfaceType As Nullable(Of Integer)
    Public Property InstallationZoneType As Nullable(Of Integer)
    Public Property InstallationDateTime As Nullable(Of Date)
    Public Property LocationDescription As String

End Class
